"""Minimal type stubs for optional prometheus_client."""
from typing import Any, List

CONTENT_TYPE_LATEST: str

class CollectorRegistry:
    pass

class Counter:
    def __init__(self, name: str, documentation: str, labelnames: List[str] = ..., registry: Any = ...) -> None: ...
    def inc(self, amount: float = ...) -> None: ...
    def labels(self, **kwargs: Any) -> "Counter": ...

class Gauge:
    def __init__(self, name: str, documentation: str, labelnames: List[str] = ..., registry: Any = ...) -> None: ...
    def set(self, value: float) -> None: ...
    def labels(self, **kwargs: Any) -> "Gauge": ...

class Histogram:
    def __init__(self, name: str, documentation: str, labelnames: List[str] = ..., buckets: tuple[Any, ...] = ..., registry: Any = ...) -> None: ...
    def observe(self, amount: float) -> None: ...
    def labels(self, **kwargs: Any) -> "Histogram": ...

def generate_latest(registry: CollectorRegistry) -> bytes: ...
