#!/usr/bin/env python3
"""
Script para restaurar releases apagadas no GitHub.

Este script:
1. Lista todas as releases no repositório local (diretório `releases/`).
2. Verifica quais releases já existem no GitHub.
3. Recria as releases que estão faltando no GitHub.
4. Marca a release mais recente como `--latest`.

Uso:
    python scripts/restore_releases.py
"""

import json
import os
import re
import subprocess
from pathlib import Path


def run_command(command: str) -> str:
    """Executa um comando shell e retorna a saída."""
    result = subprocess.run(
        command,
        shell=True,
        capture_output=True,
        text=True,
    )
    return result.stdout.strip()


def get_github_releases() -> list[dict]:
    """Retorna uma lista de releases existentes no GitHub."""
    try:
        # Usa gh CLI para listar releases
        output = run_command("gh release list --json tagName,body,name,isLatest")
        if not output:
            return []
        return json.loads(output)
    except Exception as e:
        print(f"⚠️ Erro ao listar releases do GitHub: {e}")
        return []


def get_local_releases() -> list[dict]:
    """Retorna uma lista de releases locais (diretório `releases/`)."""
    releases_dir = Path("releases")
    if not releases_dir.exists():
        print("⚠️ Diretório `releases/` não encontrado.")
        return []

    local_releases = []
    for release_dir in sorted(releases_dir.iterdir(), reverse=True):
        if release_dir.is_dir():
            meta_file = release_dir / ".meta.json"
            if meta_file.exists():
                try:
                    with open(meta_file, "r", encoding="utf-8") as f:
                        meta = json.load(f)
                    
                    # Extrair slug (ex: summer_26)
                    slug = release_dir.name
                    
                    # Extrair year e season do slug (ex: summer_26 -> v2026-summer)
                    year_short = re.search(r'\d+$', slug)
                    if not year_short:
                        continue
                    year = f"20{year_short.group()}"
                    season = slug.replace(year_short.group(), "").rstrip("_")
                    tag_name = f"v{year}-{season}"
                    
                    # Adicionar informações da release
                    local_releases.append({
                        "slug": slug,
                        "tag_name": tag_name,
                        "name": meta.get("name", slug),
                        "release_id": meta.get("release_id", 0),
                        "total_features": meta.get("total_features", sum(c.get("count", 0) for c in meta.get("categories", []))),
                        "categories": len(meta.get("categories", [])),
                        "generated_at": meta.get("generated_at", ""),
                        "meta_path": str(meta_file),
                    })
                except Exception as e:
                    print(f"⚠️ Erro ao ler {meta_file}: {e}")
    
    return local_releases


def create_github_release(release: dict) -> bool:
    """Cria uma release no GitHub."""
    tag_name = release["tag_name"]
    name = release["name"]
    total_features = release["total_features"]
    categories = release["categories"]
    generated_at = release["generated_at"]
    slug = release["slug"]
    
    # Montar as notas da release
    notes = f"## 📋 {name} Release Notes\n\n"
    notes += f"### 📊 Statistics\n"
    notes += f"| Metric | Value |\n"
    notes += f"| --- | --- |\n"
    notes += f"| Features | {total_features} |\n"
    notes += f"| Categories | {categories} |\n"
    notes += f"| Generated | {generated_at} |\n\n"
    notes += f"### 🔗 Links\n"
    notes += f"- [Full Release Notes](./releases/{slug}/)\n"
    notes += f"- [README](./README.md)\n"
    notes += f"- [Documentation](https://fatal1tybarucco.github.io/Salesforce-WebDev/)\n\n"
    notes += f"### 🏷️ Trailhead Modules\n"
    notes += f"Check individual category files for related Trailhead modules.\n\n"
    notes += f"---\n"
    notes += f"*Auto-generated by Salesforce Release Notes Pipeline*"
    
    # Criar a release no GitHub
    command = f'gh release create "{tag_name}" --title "{name}" --notes "{notes}"'
    
    try:
        result = run_command(command)
        print(f"✅ Release {tag_name} criada com sucesso.")
        return True
    except Exception as e:
        print(f"❌ Erro ao criar release {tag_name}: {e}")
        return False


def mark_latest_release() -> bool:
    """Marca a release mais recente como `--latest`."""
    try:
        # Obter a release mais recente
        output = run_command("gh release list --json tagName,isLatest --limit 1")
        if not output:
            print("⚠️ Nenhuma release encontrada para marcar como `--latest`.")
            return False
        
        releases = json.loads(output)
        if not releases:
            print("⚠️ Nenhuma release encontrada para marcar como `--latest`.")
            return False
        
        latest_tag = releases[0]["tagName"]
        
        # Marcar como latest
        command = f'gh release edit "{latest_tag}" --latest'
        run_command(command)
        print(f"✅ Release {latest_tag} marcada como `--latest`.")
        return True
    except Exception as e:
        print(f"❌ Erro ao marcar release como `--latest`: {e}")
        return False


def main():
    print("🔍 Restaurando releases apagadas no GitHub...\n")
    
    # 1. Obter releases locais e do GitHub
    local_releases = get_local_releases()
    github_releases = get_github_releases()
    
    print(f"📊 Encontradas {len(local_releases)} releases locais.")
    print(f"📊 Encontradas {len(github_releases)} releases no GitHub.")
    
    # 2. Identificar releases que precisam ser recriadas
    github_tags = {release["tagName"] for release in github_releases}
    releases_to_create = [
        release for release in local_releases 
        if release["tag_name"] not in github_tags
    ]
    
    print(f"\n📌 {len(releases_to_create)} releases precisam ser recriadas no GitHub.")
    
    # 3. Recriar releases
    for release in sorted(releases_to_create, key=lambda x: x["release_id"], reverse=True):
        print(f"\n🔧 Criando release: {release['tag_name']} (ID: {release['release_id']})...")
        success = create_github_release(release)
        if not success:
            print(f"⚠️ Falha ao criar release {release['tag_name']}.")
    
    # 4. Marcar a release mais recente como `--latest`
    print("\n🔧 Marcando a release mais recente como `--latest`...")
    mark_latest_release()
    
    print("\n✅ Processo de restauração concluído.")


if __name__ == "__main__":
    main()
