#!/bin/bash
# Script para restaurar releases apagadas no GitHub
# Uso: ./scripts/restore_releases.sh

set -euo pipefail

echo "🔍 Restaurando releases apagadas no GitHub..."

# 1. Obter a lista de releases locais (diretório releases/)
echo "\n📊 Procurando por releases locais..."
LOCAL_RELEASES=()
for RELEASE_DIR in releases/*/; do
    if [ -f "${RELEASE_DIR}.meta.json" ]; then
        SLUG=$(basename "$RELEASE_DIR")

        # Extrair year e season do slug (ex: summer_26 -> v2026-summer)
        YEAR_SHORT=$(echo "$SLUG" | grep -oP '\d+$')
        YEAR="20${YEAR_SHORT}"
        SEASON=$(echo "$SLUG" | sed 's/_[0-9]*$//')
        TAG_NAME="v${YEAR}-${SEASON}"

        # Extrair informações do .meta.json
        NAME=$(python3 -c "import json; print(json.load(open('${RELEASE_DIR}.meta.json'))['name'])")
        TOTAL_FEATURES=$(python3 -c "import json; d=json.load(open('${RELEASE_DIR}.meta.json')); print(d.get('total_features', sum(c['count'] for c in d.get('categories', []))))")
        CATEGORIES=$(python3 -c "import json; print(len(json.load(open('${RELEASE_DIR}.meta.json')).get('categories', [])))")
        DATE=$(python3 -c "import json; print(json.load(open('${RELEASE_DIR}.meta.json')).get('generated_at', ''))")
        RELEASE_ID=$(python3 -c "import json; print(json.load(open('${RELEASE_DIR}.meta.json')).get('release_id', 0))")

        LOCAL_RELEASES+=("${TAG_NAME}|${NAME}|${TOTAL_FEATURES}|${CATEGORIES}|${DATE}|${SLUG}|${RELEASE_ID}")
    fi
done

echo "📊 Encontradas ${#LOCAL_RELEASES[@]} releases locais."

# 2. Obter a lista de releases existentes no GitHub
echo "\n📊 Obtendo releases existentes no GitHub..."
EXISTING_RELEASES=$(gh release list --json tagName 2>/dev/null || echo "[]")
EXISTING_TAGS=$(echo "$EXISTING_RELEASES" | python3 -c "
import json, sys
releases = json.load(sys.stdin)
tags = [r['tagName'] for r in releases]
print(' '.join(tags))
" || echo "")

echo "📊 Encontradas $(echo "$EXISTING_TAGS" | wc -w) releases no GitHub."

# 3. Identificar releases que precisam ser recriadas
echo "\n📌 Identificando releases para recriar..."
RELEASES_TO_CREATE=()
for RELEASE in "${LOCAL_RELEASES[@]}"; do
    IFS='|' read -r TAG_NAME NAME TOTAL_FEATURES CATEGORIES DATE SLUG RELEASE_ID <<< "$RELEASE"
    if [[ ! " $EXISTING_TAGS " =~ " $TAG_NAME " ]]; then
        RELEASES_TO_CREATE+=("${TAG_NAME}|${NAME}|${TOTAL_FEATURES}|${CATEGORIES}|${DATE}|${SLUG}|${RELEASE_ID}")
    fi
done

echo "📌 ${#RELEASES_TO_CREATE[@]} releases precisam ser recriadas no GitHub."

# 4. Recriar releases
for RELEASE in "${RELEASES_TO_CREATE[@]}"; do
    IFS='|' read -r TAG_NAME NAME TOTAL_FEATURES CATEGORIES DATE SLUG RELEASE_ID <<< "$RELEASE"
    echo "\n🔧 Criando release: ${TAG_NAME} (ID: ${RELEASE_ID})..."

    # Montar as notas da release
    NOTES="## 📋 ${NAME} Release Notes"
    NOTES+="\n\n### 📊 Statistics"
    NOTES+="\n| Metric | Value |"
    NOTES+="\n| --- | --- |"
    NOTES+="\n| Features | ${TOTAL_FEATURES} |"
    NOTES+="\n| Categories | ${CATEGORIES} |"
    NOTES+="\n| Generated | ${DATE} |"
    NOTES+="\n\n### 🔗 Links"
    NOTES+="\n- [Full Release Notes](./releases/${SLUG}/)"
    NOTES+="\n- [README](./README.md)"
    NOTES+="\n- [Documentation](https://fatal1tybarucco.github.io/Salesforce-WebDev/)"
    NOTES+="\n\n### 🏷️ Trailhead Modules"
    NOTES+="\nCheck individual category files for related Trailhead modules."
    NOTES+="\n\n---"
    NOTES+="\n*Auto-generated by Salesforce Release Notes Pipeline*"

    # Criar a release no GitHub
    if gh release create "$TAG_NAME" --title "$NAME" --notes "$NOTES"; then
        echo "✅ Release ${TAG_NAME} criada com sucesso."
    else
        echo "⚠️ Falha ao criar release ${TAG_NAME}."
    fi
done

# 5. Marcar a release mais recente como `--latest`
echo "\n🔧 Marcando a release mais recente como `--latest`..."
LATEST_TAG=$(gh release list --json tagName --limit 1 | python3 -c "
import json, sys
releases = json.load(sys.stdin)
print(releases[0]['tagName'] if releases else '')
")

if [ -n "$LATEST_TAG" ]; then
    if gh release edit "$LATEST_TAG" --latest; then
        echo "✅ Release ${LATEST_TAG} marcada como `--latest`."
    else
        echo "⚠️ Falha ao marcar release ${LATEST_TAG} como `--latest`."
    fi
else
    echo "⚠️ Nenhuma release encontrada para marcar como `--latest`."
fi

echo "\n✅ Processo de restauração concluído."
